export const ProductActions = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    EDIT_PRODUCTS_AMOUNT: 'EDIT_PRODUCTS_AMOUNT',
    RECEIVED_DATA: 'RECEIVED_DATA',
    DATA_REQUEST_ERROR: 'DATA_REQUEST_ERROR'
}